title: Philosophy Inc
description: A blog that houses musings from a group of ignoramuses masquerading as philosophers. We prefer to don the philosopher mask of the ancients – when philosophy covered science, politics, and a bunch of other intellectual exercises. As such, this blog will have an eclectic assortment of articles.

baseurl: "" # the subpath of your site
url: "https://philosophy-inc.com" # the base hostname & protocol

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Paginate Settings
paginate: 5
paginate_path: "/page:num/"

permalink: /:year/:month/:day/:title/

include:
  - assets
