title: Philosophy Inc
baseurl: ""  # the subpath of your site
url: "https://philosophy-inc.com"  # the base hostname & protocol

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Paginate Settings
paginate: 5
paginate_path: "/page:num/"

permalink: /:year/:month/:day/:title/

include:
  - assets
