title: Philosophy Inc
description: A blog that houses musings from a group of ignoramuses 
masquerading as philosophers. We prefer to don the philosopher mask of the 
ancients – when philosophy covered science, politics, and a bunch of other 
intellectual exercises. As such, this blog will have an eclectic assortment of articles.

baseurl: "/Blog" # the subpath of your site
url: "https://philosophy-inc.com" # the base hostname & protocol

twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Paginate Settings
paginate: 5
paginate_path: "/Blog/page:num/"

permalink: /Blog/:year/:month/:day/:title/
